import { useEffect, useRef, useState, type ReactNode } from "react";

type Risk = "Normal" | "Alert" | "High" | "Very High";
const riskColors: Record<Risk, string> = { Normal: "#15803d", Alert: "#ca8a04", High: "#ea580c", "Very High": "#dc2626" };
const gauges = [
  { name: "Tarbela", river: "Indus", x: 343, y: 190, level: 8.2, threshold: 10, delta: .1, discharge: 136200, risk: "Normal" as Risk },
  { name: "Kalabagh", river: "Indus", x: 304, y: 250, level: 10.8, threshold: 11, delta: .2, discharge: 218400, risk: "Alert" as Risk },
  { name: "Chashma", river: "Indus", x: 287, y: 290, level: 11.4, threshold: 11, delta: .3, discharge: 264600, risk: "High" as Risk },
  { name: "Taunsa", river: "Indus", x: 271, y: 337, level: 12.8, threshold: 12, delta: .4, discharge: 312800, risk: "High" as Risk },
  { name: "Guddu", river: "Indus", x: 250, y: 399, level: 14.6, threshold: 13, delta: .4, discharge: 412800, risk: "Very High" as Risk },
  { name: "Sukkur", river: "Indus", x: 239, y: 430, level: 12.3, threshold: 13, delta: .2, discharge: 378000, risk: "Alert" as Risk },
  { name: "Kotri", river: "Indus", x: 226, y: 480, level: 7.4, threshold: 10, delta: -.1, discharge: 146800, risk: "Normal" as Risk },
  { name: "Mangla", river: "Jhelum", x: 378, y: 230, level: 9.8, threshold: 11, delta: .1, discharge: 78400, risk: "Normal" as Risk },
  { name: "Marala", river: "Chenab", x: 402, y: 264, level: 11.7, threshold: 11, delta: .3, discharge: 168200, risk: "High" as Risk },
  { name: "Shahdara", river: "Ravi", x: 415, y: 292, level: 7.2, threshold: 9, delta: .1, discharge: 32400, risk: "Normal" as Risk },
  { name: "Sulemanki", river: "Sutlej", x: 381, y: 337, level: 9.1, threshold: 10, delta: .2, discharge: 64200, risk: "Alert" as Risk },
];
const lakes = [
  { name: "Shisper Lake", region: "Hunza · Gilgit-Baltistan", index: 82, status: "High susceptibility", temp: 7.2, trigger: "Temperature rise > 5°C / 24h", color: "#dc2626" },
  { name: "Badswat Lake", region: "Ghizer · Gilgit-Baltistan", index: 67, status: "Elevated monitoring", temp: 4.8, trigger: "Lake-level rise > 0.3 m / h", color: "#ea580c" },
  { name: "Chitral glacial lakes", region: "Upper Chitral · KP", index: 49, status: "Watch in effect", temp: 3.4, trigger: "Rainfall accumulation > 20 mm", color: "#ca8a04" },
];
const reservoirs = [
  { name: "Tarbela Dam", river: "Indus", stored: 5.12, capacity: 6.49, pool: 1486, max: 1550, inflow: 136.2, outflow: 112.8 },
  { name: "Mangla Dam", river: "Jhelum", stored: 4.28, capacity: 7.39, pool: 1174, max: 1242, inflow: 78.4, outflow: 61.2 },
  { name: "Chashma Barrage", river: "Indus", stored: .19, capacity: .25, pool: 642, max: 649, inflow: 264.6, outflow: 251.4 },
];
const rivers = [
  { name: "Indus", path: "M425 112 392 135 370 159 343 190 323 218 304 250 287 290 271 337 261 366 250 399 239 430 234 451 226 480 217 510" },
  { name: "Jhelum", path: "M419 185 400 205 378 230 367 267 343 303" },
  { name: "Chenab", path: "M449 218 422 243 402 264 382 282 360 310 337 330 307 348" },
  { name: "Ravi", path: "M448 272 415 292 391 316 364 339 329 357" },
  { name: "Sutlej", path: "M448 314 412 322 381 337 354 355 329 357 292 369 261 366" },
];
const country = "M420 60 445 77 471 69 490 88 480 110 454 126 443 153 418 172 416 202 443 228 430 254 416 276 407 312 381 337 365 369 340 390 332 424 313 445 303 482 277 508 247 505 230 492 204 495 190 477 154 481 134 461 103 454 87 426 67 412 80 389 72 367 100 348 113 315 144 310 169 285 201 286 225 265 230 231 250 213 263 186 281 168 299 143 319 129 326 105 355 97 369 72 390 82Z";
const control = "rounded-sm border border-neutral-200 bg-white px-2.5 py-1.5 text-[11px] text-black hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black";

function HydroCard({ title, label, children, extra, className = "" }: { title: string; label: string; children: ReactNode; extra?: ReactNode; className?: string }) {
  return <section className={`min-h-0 overflow-hidden rounded-sm border border-neutral-200 bg-white ${className}`}><header className="flex items-center justify-between gap-2 border-b border-neutral-200 px-4 py-3"><div><p className="mb-1 text-[9px] tracking-[.15em]">{label}</p><h2 className="text-[13px] font-semibold">{title}</h2></div>{extra}</header>{children}</section>;
}

export default function HydrologyFlood() {
  const [basin, setBasin] = useState("Indus Basin");
  const [gaugeName, setGaugeName] = useState("Guddu");
  const [range, setRange] = useState("Last 24 Hours");
  const [date, setDate] = useState("2025-06-15T20:40");
  const [overlay, setOverlay] = useState("Flood extent & rivers");
  const [broadcast, setBroadcast] = useState(false);
  const [confirmBroadcast, setConfirmBroadcast] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const [selectedLake, setSelectedLake] = useState(0);
  const [sample, setSample] = useState(11);
  const [acknowledged, setAcknowledged] = useState<string[]>([]);
  const [exported, setExported] = useState(false);
  const broadcastDialog = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    if (confirmBroadcast) broadcastDialog.current?.showModal();
    else broadcastDialog.current?.close();
  }, [confirmBroadcast]);
  useEffect(() => {
    const closeExpanded = (event: KeyboardEvent) => { if (event.key === "Escape") setExpanded(false); };
    window.addEventListener("keydown", closeExpanded);
    return () => window.removeEventListener("keydown", closeExpanded);
  }, []);
  const visibleGauges = gauges.filter(gauge => basin === "Indus Basin" || `${gauge.river} Catchment` === basin);
  const gauge = gauges.find(station => station.name === gaugeName) ?? visibleGauges[0];
  const lake = lakes[selectedLake];
  const hours = range === "Historical Trend" ? 168 : range === "Real-time" ? 6 : 24;
  const offset = Math.round((new Date(date).getHours() - 20) * 1000);
  const flow = Math.max(0, Math.round(gauge.discharge * (.72 + sample * .028) + offset));
  const selectBasin = (value: string) => { setBasin(value); const candidates = gauges.filter(station => value === "Indus Basin" || `${station.river} Catchment` === value); if (!candidates.some(station => station.name === gaugeName)) setGaugeName(candidates[0].name); };
  const selectGauge = (name: string) => { const station = gauges.find(item => item.name === name)!; if (basin !== "Indus Basin" && basin !== `${station.river} Catchment`) setBasin(`${station.river} Catchment`); setGaugeName(name); };
  const timeLabel = (index: number) => new Date(new Date(`${date}+05:00`).getTime() - (11-index) / 11 * hours * 3600000).toLocaleString("en-GB", { timeZone: "Asia/Karachi", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });
  const warnings = [
    { id: "HYD-2041", gauge: "Guddu", river: "Indus", title: "Very high flood threshold exceeded", text: "Water level 14.6 m · threshold 13.0 m. Notify downstream response teams.", severity: "Very High" as Risk, age: 4 },
    { id: "HYD-2038", gauge: "Taunsa", river: "Indus", title: "Rapid river-level rise detected", text: "Rise rate +0.4 m/h. Increase gauge observation frequency.", severity: "High" as Risk, age: 18 },
    { id: "HYD-2034", gauge: "Marala", river: "Chenab", title: "Catchment flash-flood watch", text: "Localized heavy rainfall forecast across upper Chenab catchment.", severity: "High" as Risk, age: 32 },
    { id: "HYD-2029", gauge: "Sulemanki", river: "Sutlej", title: "Downstream flow advisory", text: "Rising discharge trend. Maintain readiness at low-lying settlements.", severity: "Alert" as Risk, age: 47 },
  ].filter(warning => basin === "Indus Basin" || `${warning.river} Catchment` === basin);
  const exportReport = () => { const rows = visibleGauges.map(station => [station.name,station.river,station.level,station.threshold,station.delta,station.discharge,station.risk].join(",")); const csv = `PMDNOC simulated hydrology report,${date},${basin},${range}\nGauge,River,Level_m,Warning_threshold_m,Delta_m_per_h,Discharge_cusecs,Status\n${rows.join("\n")}`; const url = URL.createObjectURL(new Blob([csv],{type:"text/csv"})); const link = document.createElement("a"); link.href=url; link.download=`PMDNOC-hydrology-${date.slice(0,10)}.csv`; link.click(); URL.revokeObjectURL(url); setExported(true); };
  return <div className="flex min-h-0 flex-1 flex-col bg-white text-black">
    <header className="flex min-h-[86px] flex-wrap items-center justify-between gap-3 border-b border-neutral-200 px-5 py-3"><div><p className="mb-1.5 text-[9px] tracking-[.18em]">HYDROLOGICAL OPERATIONS / 04</p><h1 className="text-xl font-semibold">Hydrology & Flood Monitoring</h1><p className="mt-1.5 flex items-center gap-1.5 text-[10px]"><span className="h-1.5 w-1.5 rounded-full bg-orange-600" />Active Flood Watch: {basin}</p></div><div className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-[9px] tracking-wider">BASIN / CATCHMENT<select value={basin} className={control} onChange={event => selectBasin(event.target.value)}>{["Indus Basin","Jhelum Catchment","Chenab Catchment","Ravi Catchment","Sutlej Catchment"].map(value => <option key={value}>{value}</option>)}</select></label><label className="grid gap-1 text-[9px] tracking-wider">HYDROLOGICAL GAUGE<select className={control} value={gaugeName} onChange={event => selectGauge(event.target.value)}>{visibleGauges.map(station => <option key={station.name}>{station.name}</option>)}</select></label><label className="grid gap-1 text-[9px] tracking-wider">TIME RANGE<select className={control} value={range} onChange={event => setRange(event.target.value)}>{["Real-time","Last 24 Hours","Historical Trend"].map(value => <option key={value}>{value}</option>)}</select></label><label className="grid gap-1 text-[9px] tracking-wider">REFERENCE TIME / PKT<input className={control} type="datetime-local" value={date} onChange={event => {if(event.target.value) setDate(event.target.value);}} /></label></div><div className="flex items-center gap-2"><button className={`${control} ${broadcast ? "border-red-500 bg-red-50" : ""}`} aria-pressed={broadcast} onClick={() => broadcast ? setBroadcast(false) : setConfirmBroadcast(true)}>◉ {broadcast ? "Broadcast active" : "Emergency"}</button><button className={control} onClick={exportReport}>↓ Report</button></div></header>
    <div className="flex items-center justify-between border-b border-neutral-200 px-5 py-2 text-[9px] tracking-wider"><span>FLOOD EARLY WARNING <span className="mx-3">/</span> {basin.toUpperCase()} <span className="mx-3">/</span> {visibleGauges.length} GAUGES</span><span role="status">{exported ? "CSV REPORT EXPORTED · " : ""}{broadcast ? "DEMO BROADCAST ACTIVE · " : ""}SIMULATED DATA · NOT FOR OPERATIONAL USE</span></div>
    <main className="grid min-h-0 flex-1 grid-cols-[28fr_46fr_26fr] gap-3 overflow-auto p-3">
      <div className="flex min-w-0 flex-col gap-3">
        <HydroCard title="Critical River Gauges" label="WATER LEVEL / THRESHOLD MONITORING" extra={<span className="text-[9px]">{visibleGauges.filter(station => station.risk !== "Normal").length} flagged</span>} className="flex min-h-[300px] flex-1 flex-col"><div className="min-h-0 flex-1 overflow-auto"><table className="w-full text-left text-[10px]"><thead className="sticky top-0 bg-neutral-50 text-[9px]"><tr><th className="px-3 py-3 font-medium">GAUGE / RIVER</th><th className="py-3 font-medium">LEVEL</th><th className="py-3 font-medium">Δ m/h</th><th className="py-3 pr-3 font-medium">STATUS</th></tr></thead><tbody>{visibleGauges.map(station => <tr key={station.name} className={`border-t border-neutral-200 ${gaugeName === station.name ? "bg-neutral-100" : "hover:bg-neutral-50"}`}><td className="px-3 py-3"><button className="text-left focus-visible:outline-2 focus-visible:outline-black" onClick={() => selectGauge(station.name)} aria-pressed={gaugeName===station.name}><b className="block">{station.name}</b><span className="mt-1 block text-[9px]">{station.river} · {(station.discharge/1000).toFixed(1)}K cusecs</span></button></td><td className="font-mono">{station.level.toFixed(1)} m<span className="mt-1 block text-[8px]">warn {station.threshold.toFixed(1)} m</span></td><td className="font-mono">{station.delta > 0 ? "+" : ""}{station.delta.toFixed(1)}</td><td className="pr-3"><span className="flex items-center gap-1 text-[9px]"><svg width="6" height="6"><circle cx="3" cy="3" r="3" fill={riskColors[station.risk]} /></svg>{station.risk}</span></td></tr>)}</tbody></table></div><div className="flex justify-between border-t border-neutral-200 px-3 py-2 text-[9px]"><span>DATUM: LOCAL GAUGE ZERO</span><span>Sample readings</span></div></HydroCard>
        <HydroCard title="GLOF Early Warning" label="GLACIAL LAKE SUSCEPTIBILITY" extra={<span className="text-[9px]">03 monitored</span>}><div className="p-3">{lakes.map((item,index) => <button key={item.name} className={`mb-1 w-full rounded-sm border p-2.5 text-left ${index===selectedLake ? "border-black bg-neutral-50" : "border-transparent hover:bg-neutral-50"}`} onClick={() => setSelectedLake(index)} aria-pressed={index===selectedLake}><div className="flex justify-between text-[11px]"><b>{item.name}</b><span className="font-mono">{item.index}<small className="text-[9px]"> / 100</small></span></div><div className="mt-1 flex justify-between text-[9px]"><span>{item.region}</span><span>{item.status}</span></div><svg viewBox="0 0 300 3" className="mt-2 h-1 w-full" preserveAspectRatio="none"><rect width="300" height="3" fill="#e5e5e5" /><rect width={item.index*3} height="3" fill={item.color} /></svg></button>)}<div className="mt-2 border-t border-neutral-200 px-2 pt-3 text-[10px]"><b>Trigger watch · {lake.name}</b><p className="mt-1 leading-4">{lake.trigger}</p><p className="mt-2 font-mono text-[9px]">Air temperature {lake.temp}°C · simulated sensors</p></div></div></HydroCard>
      </div>
      <div className={`flex min-h-0 min-w-0 flex-col gap-3 ${expanded ? "fixed inset-4 z-50 bg-white p-3 shadow-2xl" : ""}`}>
        <HydroCard title="Basin Flood Extent & River Network" label="GIS / HYDROLOGICAL COMMON OPERATING PICTURE" className="flex min-h-[330px] flex-1 flex-col" extra={<button className={control} onClick={() => setExpanded(!expanded)} aria-label={expanded ? "Close expanded map" : "Expand flood map"}>{expanded ? "✕ Close" : "⛶"}</button>}>
          <div className="relative min-h-0 flex-1 overflow-hidden bg-white"><div className="absolute left-3 right-3 top-3 z-10 flex items-center justify-between"><span className="rounded-sm border border-neutral-200 bg-white px-2 py-1.5 text-[9px]">{basin} · {timeLabel(sample)} PKT</span><select className={control} value={overlay} aria-label="GIS overlay layer" onChange={event => setOverlay(event.target.value)}>{["Flood extent & rivers","River network only","Gauge stations","Catchment rainfall"].map(value => <option key={value}>{value}</option>)}</select></div>
            <svg viewBox="0 0 600 580" className="h-full w-full" role="group" aria-label="Pakistan river network and simulated flood extent; select a gauge for details"><defs><pattern id="hydroGrid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#223247" strokeWidth=".6" /></pattern><clipPath id="hydroCountry"><path d={country} /></clipPath><linearGradient id="hydroFlood"><stop stopColor="#3b82f6" stopOpacity=".3" /><stop offset="1" stopColor="#38bdf8" stopOpacity=".6" /></linearGradient></defs><rect width="600" height="580" fill="url(#hydroGrid)" /><g fill="#556a80" fontSize="10" letterSpacing="2"><text x="80" y="175">AFGHANISTAN</text><text x="22" y="330">IRAN</text><text x="475" y="378">INDIA</text><text x="487" y="65">CHINA</text><text x="130" y="550">ARABIAN SEA</text></g><path d={country} fill="#1b3041" stroke="#748b9d" strokeWidth="1.2" /><g clipPath="url(#hydroCountry)">
              {Array.from({length:18},(_,index) => <path key={index} d={`M60 ${90+index*24} Q210 ${50+index*24} 330 ${100+index*23}T520 ${85+index*23}`} fill="none" stroke="#60727d" opacity=".2" />)}
              {overlay === "Flood extent & rivers" && <g><path d="M289 281 308 294 289 342 280 372 268 408 258 446 242 480 221 487 219 454 226 419 238 387 244 359 259 325Z" fill="url(#hydroFlood)" /><g className={range === "Real-time" ? "forecast-streams" : ""}><path d="M284 293 270 340 257 389 241 435 229 480" fill="none" stroke="#7dd3fc" strokeWidth="12" opacity=".3" strokeDasharray="20 14" /></g><ellipse cx="250" cy="405" rx={20+sample} ry="28" fill="#ef4444" opacity=".17" /><ellipse cx="272" cy="334" rx="19" ry="27" fill="#f97316" opacity=".18" /></g>}
              {overlay === "Catchment rainfall" && <g fill="#34d399"><ellipse cx="379" cy="183" rx="59" ry="38" opacity=".4" /><ellipse cx="402" cy="253" rx="45" ry="36" opacity=".25" /><ellipse cx="319" cy="267" rx="38" ry="54" opacity=".2" /></g>}
              {overlay !== "Gauge stations" && rivers.map(river => <path key={river.name} d={river.path} fill="none" stroke={basin === "Indus Basin" || basin === `${river.name} Catchment` ? "#60c8ff" : "#486778"} strokeWidth={river.name === "Indus" ? 3 : 1.7} />)}
            </g><g fill="#a5bdcb" fontSize="8" letterSpacing="1"><text x="352" y="295">JHELUM</text><text x="372" y="321">CHENAB</text><text x="394" y="351">RAVI</text><text x="354" y="384">SUTLEJ</text><text x="203" y="375">INDUS</text><text x="140" y="329">BALOCHISTAN</text><text x="213" y="470">SINDH</text></g>
              {visibleGauges.map(station => <g key={station.name} transform={`translate(${station.x} ${station.y})`} role="button" tabIndex={0} className="forecast-marker cursor-pointer outline-none" aria-label={`Select ${station.name}, ${station.risk}, ${station.level} meters`} onClick={() => selectGauge(station.name)} onKeyDown={event => {if(event.key === "Enter" || event.key === " ") {event.preventDefault(); selectGauge(station.name);}}}><circle r={gaugeName===station.name ? 12 : 8} fill="#0c1828" stroke={gaugeName===station.name ? "#fff" : riskColors[station.risk]} strokeWidth="1.5" /><circle r="4" fill={riskColors[station.risk]} /><text x="15" y="3" fill="#e2e8f0" fontSize="9">{station.name}</text></g>)}
              <g transform="translate(416 116)"><path d="M0-7 7 5H-7Z" fill="#f97316" /><text x="12" y="2" fill="#e2e8f0" fontSize="8">GLOF WATCH</text></g>
            </svg>
            <div className="absolute bottom-3 left-3 right-3 rounded-sm border border-neutral-200 bg-white p-3"><div className="flex items-center justify-between"><div><b className="text-[12px]">{gauge.name} Gauge</b><p className="mt-1 text-[9px]">{gauge.river} River · {gauge.risk}</p></div><div className="text-right"><b className="font-mono text-xl">{gauge.level} <small className="text-[10px]">m</small></b><p className="font-mono text-[9px]">{(flow/1000).toFixed(1)}K cusecs · {gauge.delta>0 ? "+" : ""}{gauge.delta} m/h</p></div></div><div className="mt-3 flex justify-between border-t border-neutral-200 pt-2 text-[9px]">{Object.entries(riskColors).map(([label,color]) => <span key={label} className="flex items-center gap-1"><svg width="6" height="6"><circle cx="3" cy="3" r="3" fill={color} /></svg>{label}</span>)}</div></div>
          </div>
        </HydroCard>
        <HydroCard title="River Discharge & Rainfall Timeline" label={`${gauge.name.toUpperCase()} / ${range.toUpperCase()}`} extra={<span className="font-mono text-[10px]">{(flow/1000).toFixed(1)}K cusecs</span>}>
          <div className="flex justify-between px-4 pt-3 text-[9px]"><span>━ Current discharge <span className="ml-3">┄ Historical baseline</span></span><span className="text-emerald-700">▥ Basin rainfall / mm</span></div><svg viewBox="0 0 520 145" className="h-[clamp(110px,16vh,220px)] w-full" role="img" aria-label={`${gauge.name} discharge and basin rainfall over ${hours} hours`}>
            {[25,55,85,115].map((height,index) => <g key={height}><line x1="43" x2="485" y1={height} y2={height} stroke="#e5e5e5" strokeDasharray="2 3" /><text x="5" y={height+3} fill="#171717" fontSize="8">{Math.round(gauge.discharge/1000*(1.25-index*.2))}K</text><text x="490" y={height+3} fill="#15803d" fontSize="8">{30-index*10}</text></g>)}
            {Array.from({length:12},(_,index) => <rect key={index} x={44+index*39} y={115-(index%4+1)*(range==="Historical Trend" ? 9 : 6)} width="12" height={(index%4+1)*(range==="Historical Trend" ? 9 : 6)} fill="#34d399" opacity=".45" />)}
            <path d="M44 95Q85 79 124 86T204 76T284 85T364 72T444 80L480 78" fill="none" stroke="#a3a3a3" strokeDasharray="4 3" /><path d="M44 107Q84 98 124 97T204 81T284 66T364 53T444 37L480 29" fill="none" stroke="#0284c7" strokeWidth="2" /><line x1={44+sample*39.6} x2={44+sample*39.6} y1="18" y2="119" stroke="#171717" strokeDasharray="3 3" />{[0,3,6,9,11].map(index => <text key={index} x={44+index*39.6} y="138" textAnchor="middle" fontSize="8" fill="#171717">−{Math.round((11-index)/11*hours)}h</text>)}
          </svg><div className="flex items-center gap-3 border-t border-neutral-200 px-4 py-2"><input className="h-1 flex-1 cursor-pointer accent-black" type="range" min="0" max="11" value={sample} onChange={event => setSample(Number(event.target.value))} aria-label="Inspect discharge timeline point" /><span className="font-mono text-[9px]">{timeLabel(sample)} PKT</span></div>
        </HydroCard>
      </div>
      <div className="flex min-w-0 flex-col gap-3">
        <HydroCard title="Reservoir & Dam Levels" label="STORAGE / INFLOW / OUTFLOW"><div className="p-3">{reservoirs.filter(dam => basin === "Indus Basin" || basin === `${dam.river} Catchment`).map(dam => <article key={dam.name} className="mb-3 border-b border-neutral-200 pb-3 last:mb-0 last:border-0 last:pb-0"><div className="flex justify-between text-[11px]"><button className="font-semibold underline-offset-2 hover:underline" onClick={() => selectGauge(dam.name.replace(" Dam","").replace(" Barrage",""))}>{dam.name} ↗</button><span className="font-mono">{Math.round(dam.stored/dam.capacity*100)}% full</span></div><svg viewBox="0 0 300 12" preserveAspectRatio="none" className="my-3 h-3 w-full" role="img" aria-label={`${dam.name} ${Math.round(dam.stored/dam.capacity*100)} percent full`}><rect width="300" height="12" rx="2" fill="#f5f5f5" /><rect width={dam.stored/dam.capacity*300} height="12" rx="2" fill="#38bdf8" /><path d="M285 0v12" stroke="#ea580c" strokeDasharray="2 2" /></svg><div className="flex justify-between text-[9px]"><span>Storage <b>{dam.stored} / {dam.capacity} MAF</b></span><span>Pool <b>{dam.pool} ft</b></span></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-sm border border-neutral-200 p-2"><p className="text-[9px]">INFLOW</p><b className="mt-1 block font-mono text-[15px]">{dam.inflow}K <small className="text-[8px] font-normal">cusecs</small></b></div><div className="rounded-sm border border-neutral-200 p-2"><p className="text-[9px]">OUTFLOW</p><b className="mt-1 block font-mono text-[15px]">{dam.outflow}K <small className="text-[8px] font-normal">cusecs</small></b></div></div><p className="mt-2 text-[9px]">Max pool {dam.max} ft · {(dam.max-dam.pool)*.3048 > 0 ? ((dam.max-dam.pool)*.3048).toFixed(1) : "0"} m below limit</p></article>)}{!reservoirs.some(dam => basin==="Indus Basin" || basin===`${dam.river} Catchment`) && <p className="py-5 text-[11px] leading-5">No major reservoir telemetry available for this catchment. Select the Indus Basin or Jhelum Catchment.</p>}</div></HydroCard>
        <HydroCard title="Warnings & Advisory Log" label="THRESHOLD BREACH / EVENT STREAM" extra={<span className="text-[9px]">{warnings.filter(warning => !acknowledged.includes(warning.id)).length} open</span>} className="flex min-h-[220px] flex-1 flex-col"><div className="min-h-0 flex-1 overflow-auto p-3">{warnings.map(warning => <article key={warning.id} className="mb-3 border-b border-neutral-200 pb-3"><div className="flex justify-between text-[9px]"><span className="flex items-center gap-1.5"><svg width="6" height="6"><circle cx="3" cy="3" r="3" fill={riskColors[warning.severity]} /></svg>{warning.severity.toUpperCase()}</span><span className="font-mono">{new Date(new Date(`${date}+05:00`).getTime()-warning.age*60000).toLocaleTimeString("en-GB",{timeZone:"Asia/Karachi",hour:"2-digit",minute:"2-digit"})} PKT</span></div><button className="mt-2 text-left text-[11px] font-semibold hover:underline" onClick={() => selectGauge(warning.gauge)}>{warning.title}</button><p className="mt-1 text-[10px] leading-4">{warning.text}</p><div className="mt-2 flex justify-between text-[9px]"><span className="font-mono">{warning.id}</span><button className="underline underline-offset-2 disabled:no-underline" disabled={acknowledged.includes(warning.id)} onClick={() => setAcknowledged(previous => [...previous,warning.id])}>{acknowledged.includes(warning.id) ? "✓ Acknowledged" : "Acknowledge"}</button></div></article>)}{warnings.length===0 && <p className="py-6 text-[11px]">No active advisories in this catchment.</p>}</div></HydroCard>
      </div>
    </main>
    <footer className="flex justify-between border-t border-neutral-200 px-4 py-2 font-mono text-[9px]"><span>● HYDROLOGY ENGINE READY <span className="mx-3">|</span> {visibleGauges.length} GAUGES <span className="mx-3">|</span> GLOF WATCH ENABLED</span><span>{broadcast ? "DEMO EMERGENCY MODE · " : ""}SIMULATED TELEMETRY · {date.replace("T"," ")} PKT</span></footer>
    <dialog ref={broadcastDialog} onCancel={() => setConfirmBroadcast(false)} onClose={() => setConfirmBroadcast(false)} aria-labelledby="broadcast-title" className="fixed inset-0 m-auto w-full max-w-md rounded-sm border border-neutral-300 bg-white p-6 text-black shadow-xl backdrop:bg-black/30"><h2 id="broadcast-title" className="text-lg font-semibold">Enable demo emergency broadcast?</h2><p className="mt-3 text-sm leading-6">Activate the emergency indicator for {basin}. This is a simulated control; no message is sent to agencies, operators, or the public.</p><div className="mt-5 flex justify-end gap-2"><button autoFocus className={control} onClick={() => setConfirmBroadcast(false)}>Cancel</button><button className={`${control} border-red-300 bg-red-50`} onClick={() => {setBroadcast(true);setConfirmBroadcast(false);}}>Enable demo mode</button></div></dialog>
  </div>;
}
