import { useEffect, useRef, useState, type ReactNode } from "react";

const radarSites = [
  { name: "Islamabad", code: "ISB", x: 365, y: 200, online: true, signal: 98 },
  { name: "Karachi", code: "KHI", x: 245, y: 493, online: true, signal: 94 },
  { name: "Multan", code: "MUX", x: 333, y: 345, online: true, signal: 96 },
  { name: "Lahore", code: "LHE", x: 395, y: 280, online: true, signal: 97 },
  { name: "Peshawar", code: "PEW", x: 320, y: 190, online: true, signal: 91 },
  { name: "Quetta", code: "UET", x: 190, y: 320, online: false, signal: 0 },
  { name: "Dera Ismail Khan", code: "DIK", x: 298, y: 274, online: true, signal: 89 },
  { name: "Rahim Yar Khan", code: "RYK", x: 290, y: 390, online: true, signal: 93 },
];
const products = ["Composite Reflectivity", "Radial Velocity", "VIL", "Satellite IR", "WV", "VIS", "Cloud Top Temperature"];
const channels = [{ name: "Infrared IR1", product: "Satellite IR", band: "10.8 μm", detail: "Cloud-top thermal imagery" }, { name: "Water Vapor WV", product: "WV", band: "6.2 μm", detail: "Upper-level moisture" }, { name: "Visible VIS", product: "VIS", band: "0.6 μm", detail: "Daylight cloud structure" }, { name: "Cloud Top Temperature", product: "Cloud Top Temperature", band: "CTT", detail: "Convective intensity" }];
const cells = [
  { id: "C-014", region: "Upper Punjab", x: 360, y: 244, direction: 64, speed: 38, top: 12.4, dbz: 58, vil: 34, severity: "SEVERE" },
  { id: "C-021", region: "Southern Punjab", x: 308, y: 358, direction: 48, speed: 24, top: 8.6, dbz: 46, vil: 21, severity: "MODERATE" },
  { id: "C-028", region: "Khyber Pakhtunkhwa", x: 285, y: 195, direction: 82, speed: 31, top: 10.2, dbz: 51, vil: 28, severity: "STRONG" },
];
const country = "M420 60 445 77 471 69 490 88 480 110 454 126 443 153 418 172 416 202 443 228 430 254 416 276 407 312 381 337 365 369 340 390 332 424 313 445 303 482 277 508 247 505 230 492 204 495 190 477 154 481 134 461 103 454 87 426 67 412 80 389 72 367 100 348 113 315 144 310 169 285 201 286 225 265 230 231 250 213 263 186 281 168 299 143 319 129 326 105 355 97 369 72 390 82Z";
const buttonStyle = "rounded-sm border border-neutral-200 bg-white px-2.5 py-1.5 text-[11px] text-black hover:bg-neutral-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black";

function RadarCard({ title, label, children, extra, className = "" }: { title: string; label: string; children: ReactNode; extra?: ReactNode; className?: string }) {
  return <section className={`min-h-0 overflow-hidden rounded-sm border border-neutral-200 bg-white ${className}`}><header className="flex items-center justify-between gap-2 border-b border-neutral-200 px-4 py-3"><div><p className="mb-1 text-[9px] font-medium tracking-[.15em]">{label}</p><h2 className="text-[13px] font-semibold">{title}</h2></div>{extra}</header>{children}</section>;
}

export default function RadarSatellite() {
  const [feed, setFeed] = useState("Multi-Radar Mosaic");
  const [product, setProduct] = useState(products[0]);
  const [speed, setSpeed] = useState(1);
  const [date, setDate] = useState("2025-06-15T12:00");
  const [opacity, setOpacity] = useState(80);
  const [frame, setFrame] = useState(11);
  const [playing, setPlaying] = useState(false);
  const [interval, setIntervalMinutes] = useState(10);
  const [selectedCell, setSelectedCell] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const [ranges, setRanges] = useState(true);
  const [tracks, setTracks] = useState(true);
  const [exported, setExported] = useState(false);
  const svgRef = useRef<SVGSVGElement>(null);
  const cell = cells[selectedCell];
  const satellite = ["Satellite IR", "WV", "VIS", "Cloud Top Temperature"].includes(product);
  const activeSites = feed === "Multi-Radar Mosaic" ? radarSites : radarSites.filter(site => site.name === feed);
  const unavailable = activeSites.every(site => !site.online) && !satellite;
  const timestamp = (offset: number) => new Date(new Date(`${date}Z`).getTime() + offset * interval * 60000).toLocaleTimeString("en-GB", { timeZone: "UTC", hour: "2-digit", minute: "2-digit" });
  const scanTime = (index: number) => new Date(new Date(`${date}Z`).getTime() - (index + 1) * 12000).toLocaleTimeString("en-GB", { timeZone: "UTC", hour: "2-digit", minute: "2-digit", second: "2-digit" });
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setFrame(previous => (previous + 1) % 24), 900 / speed); return () => window.clearInterval(timer); }, [playing, speed]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setExpanded(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  const exportSnapshot = () => {
    if (!svgRef.current) return;
    const snapshot = svgRef.current.cloneNode(true) as SVGSVGElement;
    snapshot.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    const caption = document.createElementNS("http://www.w3.org/2000/svg", "text");
    caption.setAttribute("x", "16"); caption.setAttribute("y", "572"); caption.setAttribute("fill", "#ffffff"); caption.setAttribute("font-size", "10");
    caption.textContent = `PMDNOC · DEMO · ${product} · ${feed} · ${date.slice(0,10)} ${timestamp(frame)}Z · Frame ${frame + 1}/24`;
    snapshot.appendChild(caption);
    const url = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(snapshot)], { type: "image/svg+xml" }));
    const link = document.createElement("a"); link.href = url; link.download = `PMDNOC-radar-${frame + 1}.svg`; link.click(); URL.revokeObjectURL(url); setExported(true);
  };
  const echoColor = (index: number) => product === "Radial Velocity" ? ["#22c55e", "#4ade80", "#ef4444", "#f87171"][index % 4] : product === "VIL" ? ["#38bdf8", "#818cf8", "#c084fc", "#f0abfc"][index % 4] : ["#22c55e", "#a3e635", "#facc15", "#fb923c", "#ef4444", "#d946ef"][index % 6];
  return <div className="flex min-h-0 flex-1 flex-col bg-white text-black">
    <header className="flex min-h-[86px] flex-wrap items-center justify-between gap-3 border-b border-neutral-200 px-5 py-3">
      <div><p className="mb-1.5 text-[9px] tracking-[.18em]">REMOTE SENSING OPERATIONS / 03</p><h1 className="text-xl font-semibold">Radar & Satellite Mosaics</h1><p className="mt-1.5 flex items-center gap-1.5 text-[10px]"><span className="h-1.5 w-1.5 rounded-full bg-emerald-700" />7 / 8 radar feeds synchronized · Quetta offline</p></div>
      <div className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-[9px] tracking-wider">FEED TYPE<select value={feed} className={buttonStyle} onChange={event => setFeed(event.target.value)}><option>Multi-Radar Mosaic</option>{radarSites.map(site => <option key={site.code}>{site.name}</option>)}</select></label><label className="grid gap-1 text-[9px] tracking-wider">PRODUCT<select value={product} className={buttonStyle} onChange={event => setProduct(event.target.value)}>{products.map(name => <option key={name}>{name}</option>)}</select></label><label className="grid gap-1 text-[9px] tracking-wider">LOOP SPEED<select value={speed} className={buttonStyle} onChange={event => setSpeed(Number(event.target.value))}>{[.5,1,2,4].map(value => <option value={value} key={value}>{value}×</option>)}</select></label><label className="grid gap-1 text-[9px] tracking-wider">START TIME / UTC<input type="datetime-local" value={date} className={buttonStyle} onChange={event => { if (event.target.value) setDate(event.target.value); }} /></label></div>
      <div className="flex items-center gap-2"><label className="grid gap-1 text-[9px]">OPACITY {opacity}%<input aria-label="Imagery layer opacity" type="range" min="0" max="100" value={opacity} onChange={event => setOpacity(Number(event.target.value))} className="w-20 accent-black" /></label><button className={buttonStyle} onClick={() => setExpanded(true)} aria-label="Expand imagery viewer">⛶</button><button className={buttonStyle} onClick={exportSnapshot}>↓ Snapshot</button></div>
    </header>
    <div className="flex justify-between border-b border-neutral-200 px-5 py-2 text-[9px] tracking-wider"><span>OBSERVATIONAL INTELLIGENCE <span className="mx-3">/</span> PAKISTAN DOMAIN <span className="mx-3">/</span> {satellite ? "SATELLITE IMAGERY" : "RADAR COMPOSITE"}</span><span role="status">{exported ? "SVG SNAPSHOT EXPORTED · " : ""}SIMULATED DATA · NOT FOR OPERATIONAL USE</span></div>
    <main className="grid min-h-0 flex-1 grid-cols-[25fr_50fr_25fr] gap-3 overflow-auto p-3">
      <div className="flex min-w-0 flex-col gap-3">
        <RadarCard title="Radar Station Status" label="NETWORK / 08 SITES" extra={<span className="text-[9px]">7 online</span>} className="flex min-h-[290px] flex-1 flex-col">
          <button className={`m-3 flex items-center justify-between rounded-sm border px-3 py-2 text-left text-[11px] ${feed === "Multi-Radar Mosaic" ? "border-black bg-neutral-100" : "border-neutral-200"}`} onClick={() => setFeed("Multi-Radar Mosaic")} aria-pressed={feed === "Multi-Radar Mosaic"}><b>Multi-Radar Mosaic</b><span>All sites ↗</span></button>
          <div className="min-h-0 flex-1 overflow-auto px-3 pb-2">{radarSites.map((site,index) => <button key={site.code} onClick={() => setFeed(site.name)} aria-pressed={feed === site.name} className={`mb-1 w-full rounded-sm border p-2.5 text-left transition-colors ${feed === site.name ? "border-black bg-neutral-100" : "border-transparent hover:bg-neutral-50"}`}><div className="flex justify-between text-[11px]"><span className="font-semibold">{site.name} <span className="ml-1 font-mono text-[9px] font-normal">{site.code}</span></span><span className="flex items-center gap-1 text-[9px]"><i className={`h-1.5 w-1.5 rounded-full ${site.online ? "bg-emerald-700" : "bg-red-600"}`} />{site.online ? "Online" : "Offline"}</span></div><div className="mt-2 flex items-end justify-between text-[9px]"><span>Last scan {site.online ? `${scanTime(index)}Z` : "— unavailable"}</span><span className="flex items-end gap-0.5" aria-label={`Signal strength ${site.signal}%`}>{[3,5,7,9].map((height,bar) => <svg key={height} width="3" height="10"><rect y={10-height} width="3" height={height} fill={site.signal > bar * 30 ? "#171717" : "#d4d4d4"} /></svg>)}<span className="ml-1 font-mono">{site.signal}%</span></span></div></button>)}</div>
          <div className="flex justify-between border-t border-neutral-200 px-4 py-2 text-[9px]"><span>SCAN CADENCE</span><b className="font-mono">6 min · simulated</b></div>
        </RadarCard>
        <RadarCard title="Satellite Channels" label="MULTISPECTRAL / PRODUCT SELECTOR"><div className="grid gap-1 p-3">{channels.map(channel => <button key={channel.product} className={`flex items-center justify-between rounded-sm border px-3 py-2.5 text-left ${product === channel.product ? "border-black bg-neutral-100" : "border-transparent hover:bg-neutral-50"}`} onClick={() => setProduct(channel.product)} aria-pressed={product === channel.product}><div><p className="text-[11px] font-semibold">{channel.name}</p><p className="mt-1 text-[9px]">{channel.detail}</p></div><span className="font-mono text-[10px]">{channel.band}</span></button>)}</div></RadarCard>
      </div>
      <section className={`flex min-h-0 min-w-0 flex-col overflow-hidden rounded-sm border border-neutral-200 bg-white ${expanded ? "fixed inset-4 z-50 shadow-2xl" : ""}`}>
        <header className="flex items-center justify-between border-b border-neutral-200 px-4 py-3"><div><p className="mb-1 text-[9px] tracking-[.15em]">PRIMARY VISUAL WORKSPACE / {satellite ? "SATELLITE" : "RADAR"}</p><h2 className="text-[13px] font-semibold">Radar & Satellite Imagery Viewer</h2></div><button className={buttonStyle} aria-label={expanded ? "Close expanded viewer" : "Expand viewer"} onClick={() => setExpanded(!expanded)}>{expanded ? "✕ Close" : "⛶"}</button></header>
        <div className="relative min-h-[300px] flex-1 overflow-hidden bg-white">
          <div className="absolute left-3 right-3 top-3 z-10 flex justify-between gap-2"><span className="rounded-sm border border-neutral-200 bg-white px-3 py-2 text-[10px]">{product} <b className="ml-2 font-mono">{timestamp(frame)}Z</b></span><div className="flex gap-1"><button className={`${buttonStyle} ${ranges ? "font-bold" : ""}`} aria-pressed={ranges} onClick={() => setRanges(!ranges)}>Ranges</button><button className={`${buttonStyle} ${tracks ? "font-bold" : ""}`} aria-pressed={tracks} onClick={() => setTracks(!tracks)}>Tracks</button></div></div>
          <svg ref={svgRef} viewBox="0 0 600 580" className="h-full w-full" role="group" aria-label={`${product} imagery for ${feed}; select a storm cell to inspect telemetry`}>
            <defs><pattern id="radarGrid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#223247" strokeWidth=".6" /></pattern><clipPath id="radarClip"><path d={country} /></clipPath><radialGradient id="cloudLayer"><stop stopColor={product === "WV" ? "#7dd3fc" : product === "Cloud Top Temperature" ? "#d946ef" : "#f8fafc"} stopOpacity=".95" /><stop offset=".55" stopColor={product === "WV" ? "#6366f1" : "#94a3b8"} stopOpacity=".65" /><stop offset="1" stopColor="#64748b" stopOpacity="0" /></radialGradient><marker id="stormArrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 6 3 0 6" fill="none" stroke="#e2e8f0" /></marker></defs>
            <rect width="600" height="580" fill="#ffffff" /><rect width="600" height="580" fill="url(#radarGrid)" />
            <g fill="#556a80" fontFamily="Inter, sans-serif" fontSize="10" letterSpacing="2"><text x="77" y="170">AFGHANISTAN</text><text x="22" y="330">IRAN</text><text x="467" y="379">INDIA</text><text x="490" y="60">CHINA</text><text x="140" y="550">ARABIAN SEA</text></g>
            <path d={country} fill="#1b3041" stroke="#748b9d" strokeWidth="1.2" />
            <g clipPath="url(#radarClip)" fill="none" stroke="#506777" strokeWidth=".8" opacity=".45">{Array.from({length:18},(_,index) => <path key={index} d={`M60 ${90+index*24} Q210 ${50+index*24} 330 ${100+index*23}T520 ${85+index*23}`} />)}<path d="M230 231 345 214 418 202M201 286 329 306 416 276M205 390 283 401 340 390" strokeDasharray="3 4" /></g>
            {ranges && !satellite && <g fill="none" stroke="#6b93a7" strokeWidth=".7">{activeSites.filter(site => site.online).map(site => <g key={site.code}>{[45,90].map(radius => <circle key={radius} cx={site.x} cy={site.y} r={radius} opacity=".28" strokeDasharray="3 4" />)}</g>)}</g>}
            {!unavailable && <g opacity={opacity / 100}>
              {satellite ? <g>{Array.from({length:9},(_,index) => <ellipse key={index} cx={200+index*25+(frame-11)*1.5} cy={130+index*35} rx={index % 2 ? 90 : 65} ry="45" fill="url(#cloudLayer)" transform={`rotate(-25 ${200+index*25} ${130+index*35})`} />)}</g> : cells.filter(storm => feed === "Multi-Radar Mosaic" || activeSites.some(site => Math.hypot(site.x-storm.x,site.y-storm.y)<145)).map((storm,stormIndex) => <g key={storm.id} transform={`translate(${storm.x+(frame-11)*1.3} ${storm.y-(frame-11)*.65}) rotate(-32)`}>{[0,1,2,3,4,5].map(band => <path key={band} d={`M${-44+band*6} 0 Q${-50+band*7} ${-33+band*4} 0 ${-27+band*3} Q${48-band*7} ${-36+band*5} ${42-band*6} 5 Q${46-band*7} ${29-band*4} 0 ${24-band*3} Q${-42+band*6} ${33-band*5} ${-44+band*6} 0Z`} fill={echoColor(band+stormIndex)} opacity=".85" />)}</g>)}
            </g>}
            <path d="M330 150 345 214 371 263 329 306 299 351 283 401 262 447 246 492" fill="none" stroke="#60a5fa" strokeWidth="1.3" opacity=".55" />
            <g fill="#90a8b7" fontSize="8" letterSpacing="1"><text x="378" y="114">GILGIT-BALTISTAN</text><text x="245" y="216">KP</text><text x="359" y="320">PUNJAB</text><text x="136" y="368">BALOCHISTAN</text><text x="239" y="454">SINDH</text></g>
            {activeSites.map(site => <g key={site.code} transform={`translate(${site.x} ${site.y})`}><path d="M0-4 4 3H-4Z" fill={site.online ? "#e2e8f0" : "#ef4444"} /><text x="7" y="3" fill="#e2e8f0" fontSize="8">{site.name}</text></g>)}
            {!unavailable && cells.map((storm,index) => <g key={storm.id} transform={`translate(${storm.x+(frame-11)*1.3} ${storm.y-(frame-11)*.65})`} role="button" tabIndex={0} aria-label={`Inspect storm ${storm.id}`} onClick={() => setSelectedCell(index)} onKeyDown={event => {if(event.key === "Enter" || event.key === " ") {event.preventDefault(); setSelectedCell(index);}}} className="forecast-marker cursor-pointer outline-none">{tracks && <><path d={`M0 0 ${storm.speed*1.5} -${storm.speed*.65}`} fill="none" stroke="#e2e8f0" strokeDasharray="4 3" markerEnd="url(#stormArrow)" /><circle cx={storm.speed*1.5} cy={-storm.speed*.65} r="8" fill="none" stroke="#e2e8f0" opacity=".45" /></>}<circle r={selectedCell===index ? 12 : 8} fill="none" stroke={selectedCell===index ? "#fff" : "#d4d4d4"} strokeWidth="1.5" /><rect x="-3" y="-3" width="6" height="6" fill="#fff" /><text x="15" y="-14" fill="#fff" fontSize="9">{storm.id}</text></g>)}
          </svg>
          {unavailable && <div className="absolute inset-0 grid place-items-center"><div className="rounded-sm border border-neutral-200 bg-white px-6 py-5 text-center"><p className="text-sm font-semibold">Quetta radar offline</p><p className="mt-2 text-xs">No scans available. Select another feed or satellite product.</p></div></div>}
          <div className="absolute bottom-3 left-3 right-3 rounded-sm border border-neutral-200 bg-white px-3 py-2"><div className="mb-1.5 flex justify-between text-[9px]"><span>{product.toUpperCase()}</span><span>{satellite ? product === "VIS" ? "ALBEDO %" : "BRIGHTNESS TEMP. °C" : product === "Radial Velocity" ? "VELOCITY m/s" : product === "VIL" ? "kg/m²" : "dBZ"}</span></div><div className={`h-2 w-full bg-gradient-to-r ${satellite ? "from-slate-400 via-sky-200 to-fuchsia-500" : product === "Radial Velocity" ? "from-green-500 via-neutral-100 to-red-500" : product === "VIL" ? "from-sky-400 via-purple-500 to-pink-300" : "from-green-500 via-yellow-400 to-fuchsia-500"}`} /><div className="mt-1 flex justify-between font-mono text-[8px]">{(satellite ? product === "VIS" ? [0,20,40,60,80,100] : [20,0,-20,-40,-60,-80] : product === "Radial Velocity" ? [-30,-20,-10,10,20,30] : product === "VIL" ? [0,10,20,30,40,50] : [5,15,25,35,45,60]).map(value => <span key={value}>{value}</span>)}</div></div>
        </div>
        <div className="border-t border-neutral-200 px-4 py-3"><div className="mb-3 flex items-center justify-between gap-2"><div className="flex gap-1.5"><button className={buttonStyle} aria-label="Previous frame" onClick={() => setFrame((frame+23)%24)}>←</button><button className={`${buttonStyle} min-w-20 bg-neutral-100`} onClick={() => setPlaying(!playing)}>{playing ? "Ⅱ Pause" : "▶ Play"}</button><button className={buttonStyle} aria-label="Next frame" onClick={() => setFrame((frame+1)%24)}>→</button><select aria-label="Loop frame interval" className={buttonStyle} value={interval} onChange={event => setIntervalMinutes(Number(event.target.value))}>{[5,10,15].map(value => <option value={value} key={value}>{value}-min intervals</option>)}</select></div><span className="font-mono text-[11px]">Frame {String(frame+1).padStart(2,"0")} / 24</span></div><input className="h-1 w-full cursor-pointer accent-black" type="range" min="0" max="23" value={frame} onChange={event => setFrame(Number(event.target.value))} aria-label="Animation frame timeline" /><div className="mt-2 flex justify-between font-mono text-[9px]">{[0,6,12,18,23].map(value => <button key={value} onClick={() => setFrame(value)} className={frame===value ? "font-bold" : ""}>{timestamp(value)}Z</button>)}</div><div className="mt-3 flex justify-between border-t border-neutral-200 pt-2 text-[9px]"><span>{date.slice(0,10)} · {feed}</span><span>{playing ? "LOOP PLAYING" : "LOOP PAUSED"} · {speed}× · {interval*23} MIN WINDOW</span></div></div>
      </section>
      <div className="flex min-w-0 flex-col gap-3">
        <RadarCard title="Storm Tracking & Analytics" label="CELL IDENTIFICATION / 03 ACTIVE" extra={<span className="h-1.5 w-1.5 rounded-full bg-orange-500" />}>
          <div className="p-3"><div className="mb-4 flex gap-1">{cells.map((storm,index) => <button key={storm.id} onClick={() => setSelectedCell(index)} aria-pressed={selectedCell===index} className={`${buttonStyle} flex-1 ${selectedCell===index ? "border-black bg-neutral-100 font-bold" : ""}`}>{storm.id}</button>)}</div><div className="flex items-center justify-between"><div><p className="text-[13px] font-semibold">{cell.region}</p><p className="mt-1 text-[9px]">Storm {cell.id} · Frame {frame+1}</p></div><span className="rounded-sm border border-orange-200 bg-orange-50 px-2 py-1 text-[9px]">{cell.severity}</span></div><div className="mt-4 grid grid-cols-2 gap-y-4 border-y border-neutral-200 py-4">{[["DIRECTION",`${cell.direction}° NE`],["VELOCITY",`${cell.speed} km/h`],["MAX ECHO TOP",`${cell.top} km`],["MAX REFLECTIVITY",`${cell.dbz + Math.round(Math.sin(frame/3)*2)} dBZ`]].map(([label,value]) => <div key={label}><p className="text-[9px]">{label}</p><p className="mt-1 font-mono text-[17px]">{value}</p></div>)}</div><div className="mt-3 flex justify-between text-[10px]"><span>Vertically integrated liquid</span><b className="font-mono">{cell.vil} kg/m²</b></div><svg viewBox="0 0 260 90" className="mt-3 h-24 w-full" role="img" aria-label={`${cell.id} projected northeast trajectory`}><defs><marker id="trajectoryArrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 6 3 0 6Z" fill="#171717" /></marker></defs><path d="M25 68 231 20" stroke="#d4d4d4" strokeWidth="16" opacity=".5" /><path d="M25 68 231 20" stroke="#171717" strokeDasharray="4 4" markerEnd="url(#trajectoryArrow)" />{[0,1,2,3].map(index => <g key={index}><circle cx={25+index*65} cy={68-index*15} r="4" fill={index===0 ? "#ea580c" : "#fff"} stroke="#171717" /><text x={25+index*65} y={85-index*15} textAnchor="middle" fontSize="8" fill="#171717">{index===0 ? "NOW" : `+${index*15}m`}</text></g>)}</svg><p className="text-[9px] leading-4">Projected path based on simulated cell motion. Track uncertainty increases with lead time.</p></div>
        </RadarCard>
        <RadarCard title="Cross-Section / Radial View" label={`${cell.id} / INTENSITY ANALYSIS`} className="flex-1"><div className="flex justify-between px-4 pt-3 text-[9px]"><span>Vertical reflectivity slice</span><span>Azimuth {cell.direction}°</span></div><svg viewBox="0 0 300 190" className="h-[clamp(130px,20vh,290px)] w-full" role="img" aria-label={`Storm ${cell.id} cross-section, altitude versus distance`}><defs><linearGradient id="sectionEcho" x1="0" y1="1" x2="0" y2="0"><stop stopColor="#22c55e" /><stop offset=".4" stopColor="#facc15" /><stop offset=".65" stopColor="#ef4444" /><stop offset="1" stopColor="#d946ef" /></linearGradient></defs><rect x="33" y="18" width="247" height="133" fill="#101b2a" />{[35,70,105,140].map((value,index) => <g key={value}><line x1="33" x2="280" y1={value} y2={value} stroke="#344155" strokeDasharray="2 3" /><text x="8" y={value+3} fontSize="8" fill="#171717">{12-index*4}</text></g>)}<path d={`M38 147 66 133 91 139 108 115 125 83 143 ${35+selectedCell*12} 158 ${25+selectedCell*10} 174 70 191 100 216 119 245 133 277 147Z`} fill="url(#sectionEcho)" opacity=".85" /><path d="M83 147 112 130 142 83 159 61 177 108 204 135 242 147Z" fill="#ef4444" opacity=".65" />{[0,20,40,60,80].map((distance,index) => <text key={distance} x={35+index*60} y="166" fill="#171717" fontSize="8" textAnchor="middle">{distance}</text>)}<text x="116" y="185" fontSize="8" fill="#171717">DISTANCE (km)</text><text x="8" y="13" fontSize="8" fill="#171717">km</text></svg><div className="mx-4 mb-4 flex justify-between border-t border-neutral-200 pt-3 text-[10px]"><span>Echo top <b>{cell.top} km</b></span><span>Peak <b>{cell.dbz} dBZ</b></span></div></RadarCard>
      </div>
    </main>
    <footer className="flex justify-between border-t border-neutral-200 px-4 py-2 font-mono text-[9px]"><span>● MOSAIC ENGINE READY <span className="mx-3">|</span> 7 / 8 RADARS <span className="mx-3">|</span> {product.toUpperCase()}</span><span>DEMO IMAGERY · {date.slice(0,10)} {timestamp(frame)} UTC</span></footer>
  </div>;
}
